### PR TITLE
Revert "fix: parsing of In filters"

### PR DESCRIPTION
**Pull request by yusufpapurcu**
Reverts supabase/postgrest-go#13 Could you explain problem with issue and wait us for review? Also why you added panic into function?

### CODE REVIEW

**Comment by darora** [comment]
Hey @yusufpapurcu - the old implementation is completely broken:

- regexp call is passed the arguments in the wrong order. This isn't being detected at the moment because the error returned is just being thrown away; I'm no longer ignoring it which is why there's a panic (shouldn't be triggered unless someone changes the pattern)
- if the regexp didn't match (i.e. reserved characters are not present), the value is just discarded outright
- even if the regexp matches, the value stored is the literal string `"cleanValue"`, rather than the cleanValue
- not a correctness issue, but the naming is confusing: `cleanValue` is not cleaned in any way, whereas `values` is (but `value` isn't)

**Comment by inian** [comment]
Side note - should we add `.` and `;` to the regex? [ref](https://postgrest.org/en/stable/api.html#reserved-characters)

**Comment by yusufpapurcu** [comment]
> * regexp call is passed the arguments in the wrong order. This isn't being detected at the moment because the error returned is just being thrown away; I'm no longer ignoring it which is why there's a panic (shouldn't be triggered unless someone changes the pattern)

That's a huge mistake I'm sorry for this. You're right we need change this. I will test new form of In filter and reverse commits if it works. Also we can use `regexp.MustCompile`. This function panics if pattern wrong.

**Comment by yusufpapurcu** [comment]
Ok I reversed my revert commit.
Thanks for help 💯

**Pull request merged**
